In [2]:
import pandas as pd

In [29]:
data = pd.read_csv("E:/kaggledatabase/concrete.csv")
df = data.copy()
# 随机抽取一些数据
df = df.sample(frac=1.0,random_state=1)  # 全部打乱
cut_idx = int(round(0.75 * df.shape[0]))
df_train, df_test = df.iloc[:cut_idx], df.iloc[cut_idx:]
# 分割数组
df_train_x = df_train[['cement', 'slag', 'ash', 'water', 'superplastic', 'coarseagg',
       'fineagg', 'age']].values
df_train_y = df_train[['strength']].values

df_test_x = df_test[['cement', 'slag', 'ash', 'water', 'superplastic', 'coarseagg',
       'fineagg', 'age']].values
df_test_y = df_test[['strength']].values

In [30]:
cut_idx

772

In [31]:
df_test_x[0].reshape(8,1)

AttributeError: 'numpy.ndarray' object has no attribute 'scale'

In [45]:
import numpy as np
df_test_x / max(df_test_x) + 0.01

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [16]:
df_train.columns


Index(['cement', 'slag', 'ash', 'water', 'superplastic', 'coarseagg',
       'fineagg', 'age', 'strength'],
      dtype='object')

In [15]:
df_test.head()

cement   slag    ash  water  superplastic  coarseagg  fineagg  age  \
0   236.0  157.0    0.0  192.0           0.0      972.6    749.1   90   
1   393.0    0.0    0.0  192.0           0.0      940.0    758.0   90   
2   213.5    0.0  174.2  154.6          11.7     1052.3    775.5   14   
3   155.0  183.0    0.0  193.0           9.0     1047.0    697.0   28   
4   310.0    0.0    0.0  192.0           0.0      970.0    850.0    7   

   strength  
0     47.78  
1     48.79  
2     33.70  
3     18.28  
4     14.99

In [39]:
a = np.array([2],ndmin=2)
b = np.array([1,2],ndmin=2)

In [40]:
b.shape

(1, 2)

In [41]:
b * a

array([[2, 4]])

In [42]:
b

array([[1, 2]])

In [43]:
a * b

array([[2, 4]])